name: Release MegaSDK-REST

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - linux/amd64
          - linux/arm64/v8
          - linux/arm/v7
        include:
          -
            arch: linux/amd64
            dist: amd64
          -
            arch: linux/arm64/v8
            dist: arm64
          -
            arch: linux/arm/v7
            dist: armv7
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Create outputs folder
        run: mkdir outputs
      -
        name: Build MegaSDK-REST
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.arch }}
          outputs: type=tar,dest=outputs/dist-${{ matrix.dist }}.tar
          build-args: |
            CPU_ARCH=${{ matrix.dist }}
          push: false
          tags: megasdkrest:latest
      -
        name: Extract artifacts
        run: |
          cd outputs
          tar xf dist-${{ matrix.dist }}.tar
          rm -rf *.tar
          chmod a+x megasdkrest-${{ matrix.dist }}
          tar -czf megasdkrest-${{ matrix.dist }}.tar.gz megasdkrest-${{ matrix.dist }}
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: megasdkrest-${{ matrix.dist }}
          path: outputs/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      -
        run: |
          mkdir outputs
          cp artifacts/megasdkrest-amd64/* outputs/
          cp artifacts/megasdkrest-arm64/* outputs/
          cp artifacts/megasdkrest-armv7/* outputs/
      -
        name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Version 0.1.1
          files: |
            outputs/*
